/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface PageLabs {
    }
    interface SiteNav {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageLabsElement extends Components.PageLabs, HTMLStencilElement {
    }
    var HTMLPageLabsElement: {
        prototype: HTMLPageLabsElement;
        new (): HTMLPageLabsElement;
    };
    interface HTMLSiteNavElement extends Components.SiteNav, HTMLStencilElement {
    }
    var HTMLSiteNavElement: {
        prototype: HTMLSiteNavElement;
        new (): HTMLSiteNavElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-home": HTMLPageHomeElement;
        "page-labs": HTMLPageLabsElement;
        "site-nav": HTMLSiteNavElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface PageLabs {
    }
    interface SiteNav {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-home": PageHome;
        "page-labs": PageLabs;
        "site-nav": SiteNav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-labs": LocalJSX.PageLabs & JSXBase.HTMLAttributes<HTMLPageLabsElement>;
            "site-nav": LocalJSX.SiteNav & JSXBase.HTMLAttributes<HTMLSiteNavElement>;
        }
    }
}
